### ISSUE TITLE
Syntax highlighting - as of Build 3103 (Feb 9, 2016)

### ISSUE THREAD

**Issue by OmranAbazid** [kenwheeler/brogrammer-theme#33] opened 2016-02-12 22:29 UTC
As of Build 3103 (Feb 9, 2016) Javascript syntax highlighting is no longer working properly. It may be related to scope.

**Comment by anilmujagic** [comment] 2016-02-15 11:53
Yes, it's brown all over the place.

![brogrammerthemeissue](https://cloud.githubusercontent.com/assets/902307/13047981/ff0eabc6-d3e2-11e5-859f-f78e515bcc9b.png)

**Comment by ankitkhedekar** [comment] 2016-02-15 13:43
Facing same issue with js syntax highlighting since last update.

**Comment by furyscript** [comment] 2016-02-15 17:07
+1 same issue

**Comment by kenwheeler** [comment] 2016-02-16 01:21
Should be fixed now

**Comment by anilmujagic** [comment] 2016-02-16 09:45
IIRC function args were in cyan color before? That gave a nice touch. Would you consider to bring it back?
Cheers!

**Comment by OmranAbazid** [comment] 2016-02-16 18:02
Add this to your theme setting if you want the args color :

		<dict>
			<key>name</key>
			<string>Function argument</string>
			<key>scope</key>
			<string>variable.parameter</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#FD971F</string>
			</dict>
		</dict>

**Comment by honpery** [comment] 2016-02-20 10:02
+1

**Comment by honpery** [comment] 2016-02-20 10:27
I find a method to fixed this issure:

edit brogrammer.tmTheme file' 117 lines:

`
before:
#ffffff

to:
#f1c40f
`

**Comment by kenwheeler** [comment] 2016-02-20 13:14
can anyone help? I'm slammed right now and I dont have time to review what actually changed in ST

**Comment by honpery** [comment] 2016-02-20 15:03
1. By package control remove brogrammer.

2. install by this [method](https://github.com/kenwheeler/brogrammer-theme#manual)
> 1. Download the .zip
> 2. Unzip and rename the folder to Theme - Brogrammer
> 3. Copy the folder into Packages directory, which you can find using the menu item Preferences -> Browse Packages... in Sublime Text

3. edit `Brogrammer.sublime-theme` file in 141 lines:
before: #fffffff
to: ##e67e22

BUG's reason:
the lastest commit :[link](https://github.com/kenwheeler/brogrammer-theme/commit/317e1f1be8751065201a2da5afaf20c76a38baef) fixed  syntax, but it's also ace on javascript.

ps. Englishisn't well, do you want to help me ?  T T

**Comment by OmranAbazid** [comment] 2016-02-20 15:46
the current version is working
the only problem is the argument color which was orange before and now it is white.

**Comment by aleasto** [comment] 2017-01-13 22:52
I still have this problem... Tried both installation methods, but the problem is always there.
I'm on Sublime Text 3, any solution?
Edit: Nevermind, downloaded last release from github, it works now.

**Closed** 2017-11-28 19:56 UTC
